const KEY='zeitzwerk_v1_entries';
let entries=JSON.parse(localStorage.getItem(KEY)||'[]');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const euro=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n||0);
const minsToText=m=>`${String(Math.floor((m||0)/60)).padStart(2,'0')}:${String((m||0)%60).padStart(2,'0')}`;
const dateDE=s=>new Date(s+'T12:00:00').toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'});
const shortDate=s=>s?new Date(s+'T12:00:00').toLocaleDateString('de-DE'):'—';
const today=()=>new Date().toISOString().slice(0,10);
const LOCK_KEY='zeitzwerk_device_lock_v1';
let lockState={enabled:false,pinHash:'',delay:1};
let lockTimer=null, hiddenAt=null;
try{lockState={...lockState,...JSON.parse(localStorage.getItem(LOCK_KEY)||'{}')}}catch{}
function saveLockState(){localStorage.setItem(LOCK_KEY,JSON.stringify(lockState))}
async function hashPin(pin){const data=new TextEncoder().encode('zeitzwerk:'+pin);const hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function validPin(pin){return /^\d{4,6}$/.test(pin)}
function closeSheets(){['menu','aboutBox','lockBox'].forEach(id=>{let el=$('#'+id);if(el)el.classList.add('hidden')})}
function showApp(){clearTimeout(lockTimer);$('#lockScreen').classList.add('hidden');$('#lockScreen').setAttribute('aria-hidden','true');$('#app').classList.remove('hidden');$('#unlockPin').value='';$('#unlockError').textContent=''}
function lockApp(){if(!lockState.enabled)return;clearTimeout(lockTimer);closeSheets();$('#app').classList.add('hidden');$('#lockScreen').classList.remove('hidden');$('#lockScreen').setAttribute('aria-hidden','false');$('#unlockPin').value='';$('#unlockError').textContent='';setTimeout(()=>$('#unlockPin').focus(),100)}
async function checkPin(pin){return lockState.enabled&&await hashPin(pin)===lockState.pinHash}
function refreshLockSettings(){let on=!!lockState.enabled;$('#lockStatus').textContent=on?'Die App-Sperre ist auf diesem Gerät eingeschaltet.':'Die App-Sperre ist ausgeschaltet.';$('#enableLock').classList.toggle('hidden',on);['changePin','lockDelayWrap','lockNow','disableLock'].forEach(id=>$('#'+id).classList.toggle('hidden',!on));$('#lockDelay').value=String(lockState.delay??1)}
async function promptNewPin(){let p1=prompt('Neue PIN festlegen (4 bis 6 Ziffern):','');if(p1===null)return null;if(!validPin(p1)){alert('Bitte eine PIN mit 4 bis 6 Ziffern eingeben.');return null}let p2=prompt('PIN zur Bestätigung erneut eingeben:','');if(p2===null)return null;if(p1!==p2){alert('Die beiden PIN-Eingaben stimmen nicht überein.');return null}return p1}
async function requireCurrentPin(){let p=prompt('Aktuelle PIN eingeben:','');if(p===null)return false;if(!await checkPin(p)){alert('Die PIN ist nicht richtig.');return false}return true}
function pauseToMins(v){if(typeof v==='number')return v;if(!v)return 0;let [h,m]=String(v).split(':').map(Number);return (h||0)*60+(m||0)}
function calcMins(start,end,pause){if(!start||!end)return 0;let [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);let a=sh*60+sm,b=eh*60+em;if(b<a)b+=1440;return Math.max(0,b-a-pauseToMins(pause))}
function normalizeEntries(){entries=entries.map(e=>({...e,pause:pauseToMins(e.pause),billedAt:e.billedAt||null,paidAt:e.paidAt||null}))}
normalizeEntries();
function save(){localStorage.setItem(KEY,JSON.stringify(entries));render()}
function totals(list){return list.reduce((a,e)=>{a.m+=(+e.minutes||0);a.p+=(+e.amount||0);a.n++;return a},{m:0,p:0,n:0})}
function nav(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));if(id==='calendar')renderList();if(id==='billing')renderBilling()}
function render(){let now=new Date(),ym=now.toISOString().slice(0,7),month=entries.filter(e=>e.date.startsWith(ym)),open=entries.filter(e=>e.status==='open'),paid=entries.filter(e=>e.status==='paid');let a=totals(open),m=totals(month),p=totals(paid);$('#openPay').textContent=euro(a.p);$('#openMeta').textContent=`${new Set(open.map(e=>e.date)).size} Tage · ${minsToText(a.m)} Std.`;$('#monthHours').textContent=minsToText(m.m)+' Std.';$('#monthPay').textContent=euro(m.p)+' gesamt';$('#paidPay').textContent=euro(p.p);$('#paidMeta').textContent=p.n+' Einträge';renderRecent();renderList();renderBilling()}
function renderRecent(){let x=[...entries].sort((a,b)=>b.date.localeCompare(a.date)||b.created-a.created).slice(0,4);$('#recent').innerHTML=x.length?x.map(e=>rowHTML(e,false)).join(''):'<div class="hint">Noch keine Arbeitszeiten gespeichert.</div>';bindRows($('#recent'))}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function statusLabel(s){return s==='open'?'Offen':s==='billed'?'Abgerechnet':'Bezahlt'}
function rowHTML(e,inDay=true,index=0){let extra=e.status==='paid'&&e.paidAt?`<div class="meta paydate">Bezahlt am ${shortDate(e.paidAt.slice(0,10))}</div>`:e.status==='billed'&&e.billedAt?`<div class="meta paydate">Abgerechnet am ${shortDate(e.billedAt.slice(0,10))}</div>`:'';return `<div class="row" data-id="${e.id}"><div class="rowtop"><div><b>${inDay?'Einsatz '+(index+1):dateDE(e.date)}</b><div class="meta">${e.start}–${e.end} · Pause ${minsToText(e.pause)} · ${minsToText(e.minutes)} Std.</div>${e.note?`<div class="meta">${esc(e.note)}</div>`:''}${extra}</div><div class="money">${euro(e.amount)}</div></div><span class="status ${e.status}">${statusLabel(e.status)}</span><div class="rowactions"><button data-action="next">${e.status==='open'?'Als abgerechnet':e.status==='billed'?'Als bezahlt':'Wieder öffnen'}</button><button data-action="edit">Bearbeiten</button><button data-action="delete" class="danger">Löschen</button></div></div>`}
function renderList(){if(!$('#entries'))return;let f=$('#filter').value,m=$('#monthFilter').value;let list=[...entries].filter(e=>(f==='all'||e.status===f)&&(!m||e.date.startsWith(m))).sort((a,b)=>b.date.localeCompare(a.date)||a.start.localeCompare(b.start));let groups={};list.forEach(e=>(groups[e.date]??=[]).push(e));$('#entries').innerHTML=Object.entries(groups).map(([d,arr])=>{let t=totals(arr),allPaid=arr.every(e=>e.status==='paid'),allBilled=arr.every(e=>e.status==='billed'),nextStatus=allPaid?'open':allBilled?'paid':'billed',buttonText=nextStatus==='billed'?'Tag abrechnen':nextStatus==='paid'?'Tag als bezahlt':'Tag wieder öffnen';return `<div class="day" data-date="${d}"><div class="dayhead"><span>${dateDE(d)}</span><span class="daytotal">${minsToText(t.m)} Std. · ${euro(t.p)}</span></div><div class="dayactions"><button data-day-status="${nextStatus}">${buttonText}</button></div>${arr.map((e,i)=>rowHTML(e,true,i)).join('')}</div>`}).join('')||'<div class="hint">Für diese Auswahl gibt es keine Einträge.</div>';bindRows($('#entries'));bindDayActions()}
function askPaidDate(){let d=prompt('Bezahlt am (JJJJ-MM-TT):',today());if(d===null)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(d))return alert('Bitte Datum im Format JJJJ-MM-TT eingeben.'),null;return d}
function applyStatus(e,status,paidDate=null){e.status=status;if(status==='billed'){e.billedAt=e.billedAt||new Date().toISOString();e.paidAt=null}else if(status==='paid'){e.paidAt=(paidDate||today())+'T12:00:00';e.billedAt=e.billedAt||new Date().toISOString()}else{e.billedAt=null;e.paidAt=null}}
function bindRows(root){root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{let id=b.closest('.row').dataset.id,e=entries.find(x=>x.id===id);if(!e)return;if(b.dataset.action==='delete'){if(confirm('Diesen Arbeitseintrag wirklich löschen?')){entries=entries.filter(x=>x.id!==id);save()}}else if(b.dataset.action==='next'){let target=e.status==='open'?'billed':e.status==='billed'?'paid':'open',pd=target==='paid'?askPaidDate():null;if(target==='paid'&&!pd)return;applyStatus(e,target,pd);save()}else{loadEdit(e)}})}
function bindDayActions(){$$('#entries [data-day-status]').forEach(b=>b.onclick=()=>{let day=b.closest('.day').dataset.date,target=b.dataset.dayStatus,dayEntries=entries.filter(e=>e.date===day),pd=target==='paid'?askPaidDate():null;if(target==='paid'&&!pd)return;let question=target==='billed'?'Alle Einsätze dieses Tages als abgerechnet markieren?':target==='paid'?'Alle Einsätze dieses Tages als bezahlt markieren?':'Alle Einsätze dieses Tages wieder öffnen?';if(!confirm(question))return;dayEntries.forEach(e=>applyStatus(e,target,pd));save()})}
function loadEdit(e){nav('entry');$('#date').value=e.date;$('#start').value=e.start;$('#end').value=e.end;$('#pause').value=minsToText(e.pause);$('#rate').value=e.rate;$('#note').value=e.note||'';$('#entryForm').dataset.edit=e.id;updateCalc();window.scrollTo(0,0)}
function updateCalc(){let m=calcMins($('#start').value,$('#end').value,$('#pause').value),amt=m/60*(+$('#rate').value||0);$('#calc .calcValue').textContent=`${minsToText(m)} Std. · ${euro(amt)}`}
$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));['start','end','pause','rate'].forEach(id=>$('#'+id).addEventListener('input',updateCalc));
$('#entryForm').onsubmit=e=>{e.preventDefault();let pause=pauseToMins($('#pause').value),m=calcMins($('#start').value,$('#end').value,pause);if(m<=0)return alert('Bitte Arbeitszeit und Pause prüfen.');let obj={id:$('#entryForm').dataset.edit||crypto.randomUUID(),date:$('#date').value,start:$('#start').value,end:$('#end').value,pause,rate:+$('#rate').value||0,note:$('#note').value.trim(),minutes:m,amount:Math.round(m/60*(+$('#rate').value||0)*100)/100,status:'open',created:Date.now(),billedAt:null,paidAt:null};let old=entries.find(x=>x.id===obj.id);if(old){obj.status=old.status;obj.created=old.created;obj.billedAt=old.billedAt;obj.paidAt=old.paidAt;entries=entries.map(x=>x.id===obj.id?obj:x)}else entries.push(obj);delete $('#entryForm').dataset.edit;let rate=obj.rate;$('#entryForm').reset();$('#date').value=today();$('#rate').value=rate;$('#pause').value='00:00';save();nav('overview')}
$('#filter').onchange=renderList;$('#monthFilter').onchange=renderList;$('#billingMonth').onchange=renderBilling;
function billingRows(list){return list.length?list.sort((a,b)=>b.date.localeCompare(a.date)||a.start.localeCompare(b.start)).map(e=>`<div class="billrow"><div><b>${shortDate(e.date)} · ${e.start}–${e.end}</b><div class="meta">${minsToText(e.minutes)} Std.${e.note?' · '+esc(e.note):''}</div></div><strong>${euro(e.amount)}</strong></div>`).join(''):'<div class="hint compact">Keine Einträge.</div>'}
function renderBilling(){if(!$('#billingMonth'))return;let m=$('#billingMonth').value,list=entries.filter(e=>!m||e.date.startsWith(m)),open=list.filter(e=>e.status==='open'),billed=list.filter(e=>e.status==='billed'),paid=list.filter(e=>e.status==='paid'),to=totals(open),tb=totals(billed),tp=totals(paid);$('#billOpen').textContent=euro(to.p);$('#billBilled').textContent=euro(tb.p);$('#billPaid').textContent=euro(tp.p);$('#billOpenMeta').textContent=minsToText(to.m)+' Std.';$('#billBilledMeta').textContent=minsToText(tb.m)+' Std.';$('#billPaidMeta').textContent=minsToText(tp.m)+' Std.';$('#billingDetails').innerHTML=`<details open><summary>Offen (${open.length})</summary>${billingRows(open)}</details><details><summary>Abgerechnet (${billed.length})</summary>${billingRows(billed)}</details><details><summary>Bezahlt (${paid.length})</summary>${billingRows(paid)}</details>`}
$('#menuBtn').onclick=()=>$('#menu').classList.remove('hidden');$('#closeMenu').onclick=()=>$('#menu').classList.add('hidden');$('#about').onclick=()=>{$('#menu').classList.add('hidden');$('#aboutBox').classList.remove('hidden')};$('#closeAbout').onclick=()=>$('#aboutBox').classList.add('hidden');
$('#lockSettings').onclick=()=>{$('#menu').classList.add('hidden');refreshLockSettings();$('#lockBox').classList.remove('hidden')};
$('#closeLockBox').onclick=()=>$('#lockBox').classList.add('hidden');
$('#enableLock').onclick=async()=>{let pin=await promptNewPin();if(!pin)return;lockState.enabled=true;lockState.pinHash=await hashPin(pin);lockState.delay=1;saveLockState();refreshLockSettings();alert('App-Sperre ist auf diesem Gerät eingeschaltet.');};
$('#changePin').onclick=async()=>{if(!await requireCurrentPin())return;let pin=await promptNewPin();if(!pin)return;lockState.pinHash=await hashPin(pin);saveLockState();alert('Die PIN wurde geändert.');};
$('#disableLock').onclick=async()=>{if(!await requireCurrentPin())return;if(!confirm('App-Sperre auf diesem Gerät wirklich ausschalten?'))return;lockState={enabled:false,pinHash:'',delay:1};saveLockState();refreshLockSettings();alert('App-Sperre ist ausgeschaltet.');};
$('#lockDelay').onchange=()=>{lockState.delay=Number($('#lockDelay').value);saveLockState()};
$('#lockNow').onclick=()=>{if(!lockState.enabled)return;$('#lockBox').classList.add('hidden');lockApp()};
$('#unlockForm').onsubmit=async e=>{e.preventDefault();let pin=$('#unlockPin').value.trim();if(await checkPin(pin)){showApp()}else{$('#unlockError').textContent='PIN nicht richtig.';$('#unlockPin').select()}};
$('#unlockPin').addEventListener('input',()=>{$('#unlockPin').value=$('#unlockPin').value.replace(/\D/g,'').slice(0,6);$('#unlockError').textContent=''});
document.addEventListener('visibilitychange',()=>{if(!lockState.enabled)return;if(document.hidden){hiddenAt=Date.now();clearTimeout(lockTimer);let delay=(Number(lockState.delay)||0)*60000;if(delay===0)lockApp();else lockTimer=setTimeout(lockApp,delay)}else{clearTimeout(lockTimer);if(hiddenAt!==null){let delay=(Number(lockState.delay)||0)*60000;if(Date.now()-hiddenAt>=delay)lockApp();hiddenAt=null}}});
function download(name,text,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#backup').onclick=()=>download(`zeitzwerk-backup-${today()}.json`,JSON.stringify({app:'Zeit(z)Werk',version:'1.1.2g TEST',exported:new Date().toISOString(),entries},null,2),'application/json');
$('#restore').onchange=async ev=>{let f=ev.target.files[0];if(!f)return;try{let j=JSON.parse(await f.text());if(!Array.isArray(j.entries))throw 0;if(confirm(`${j.entries.length} Einträge aus der Sicherung laden? Die aktuellen Daten werden ersetzt.`)){entries=j.entries;normalizeEntries();save();alert('Datensicherung wurde wiederhergestellt.')}}catch{alert('Diese Datei ist keine gültige Zeit(z)Werk-Sicherung.')}ev.target.value=''};
$('#csv').onclick=()=>{let h=['Datum','Beginn','Ende','Pause','Netto_Std','Stundenlohn_EUR','Betrag_EUR','Status','Abgerechnet_am','Bezahlt_am','Notiz'];let lines=[h,...[...entries].sort((a,b)=>a.date.localeCompare(b.date)).map(e=>[e.date,e.start,e.end,minsToText(e.pause),(e.minutes/60).toFixed(2).replace('.',','),e.rate.toFixed(2).replace('.',','),e.amount.toFixed(2).replace('.',','),statusLabel(e.status),e.billedAt?e.billedAt.slice(0,10):'',e.paidAt?e.paidAt.slice(0,10):'',e.note||''])];download('zeitzwerk-export.csv','\ufeff'+lines.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n'),'text/csv;charset=utf-8')};
function printFiltered(openOnly){
 let month=$('#billingMonth').value||today().slice(0,7), list=entries.filter(e=>e.date.startsWith(month)&&(!openOnly||e.status==='open')).sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start));
 if(!list.length)return alert('Für diese Auswahl gibt es keine Einträge.');
 let t=totals(list), monthLabel=new Date(month+'-01T12:00:00').toLocaleDateString('de-DE',{month:'long',year:'numeric'});
 let rows=list.map(e=>`<tr><td>${shortDate(e.date)}</td><td>${e.start}</td><td>${e.end}</td><td>${minsToText(e.pause)}</td><td>${minsToText(e.minutes)}</td><td>${euro(e.rate)}</td><td>${euro(e.amount)}</td><td>${statusLabel(e.status)}</td><td>${esc(e.note||'')}</td></tr>`).join('');
 let old=$('#printSheet'); if(old)old.remove();
 let sheet=document.createElement('section'); sheet.id='printSheet';
 sheet.innerHTML=`<div class="printTop"><div><h1>Zeit(z)Werk</h1><p>Arbeitszeitnachweis</p></div><div class="printPeriod">${openOnly?'Offene Einträge · ':''}${monthLabel}</div></div><table><thead><tr><th>Datum</th><th>Beginn</th><th>Ende</th><th>Pause</th><th>Arbeitszeit</th><th>Stundenlohn</th><th>Betrag</th><th>Status</th><th>Notiz</th></tr></thead><tbody>${rows}<tr class="printSum"><td colspan="4">Gesamt</td><td>${minsToText(t.m)}</td><td></td><td>${euro(t.p)}</td><td colspan="2"></td></tr></tbody></table><div class="printFooter">powered by viacruz · viacruz.com</div>`;
 document.body.appendChild(sheet);
 let oldTitle=document.title; document.title='Zeit(z)Werk – Arbeitszeitnachweis';
 const restoreTitle=()=>{document.title=oldTitle;window.removeEventListener('afterprint',restoreTitle)};
 window.addEventListener('afterprint',restoreTitle);
 // iOS/Safari braucht Zeit, den dynamisch erzeugten Druckbereich zu layouten.
 // Das Druckblatt bleibt danach unsichtbar/offscreen im DOM und wird erst beim nächsten Druck ersetzt.
 requestAnimationFrame(()=>requestAnimationFrame(()=>setTimeout(()=>window.print(),300)));
}
$('#printOpen').onclick=()=>printFiltered(true);$('#printAll').onclick=()=>printFiltered(false);
$('#date').value=today();$('#monthFilter').value=today().slice(0,7);$('#billingMonth').value=today().slice(0,7);setTimeout(()=>{$('#splash').classList.add('hidden');render();if(lockState.enabled)lockApp();else showApp()},1200);
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
