const KEY='zeitzwerk_v1_entries';let entries=JSON.parse(localStorage.getItem(KEY)||'[]');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const euro=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n||0);
const minsToText=m=>`${Math.floor(m/60)}:${String(m%60).padStart(2,'0')}`;
const dateDE=s=>new Date(s+'T12:00:00').toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'});
function calcMins(start,end,pause){if(!start||!end)return 0;let [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);let a=sh*60+sm,b=eh*60+em;if(b<a)b+=1440;return Math.max(0,b-a-(+pause||0))}
function save(){localStorage.setItem(KEY,JSON.stringify(entries));render()}
function totals(list){return list.reduce((a,e)=>{a.m+=e.minutes;a.p+=e.amount;a.n++;return a},{m:0,p:0,n:0})}
function nav(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));if(id==='calendar')renderList()}
function render(){let now=new Date(),ym=now.toISOString().slice(0,7),month=entries.filter(e=>e.date.startsWith(ym)),open=entries.filter(e=>e.status==='open'),paid=entries.filter(e=>e.status==='paid');let a=totals(open),m=totals(month),p=totals(paid);$('#openPay').textContent=euro(a.p);$('#openMeta').textContent=`${new Set(open.map(e=>e.date)).size} Tage · ${minsToText(a.m)} Std.`;$('#monthHours').textContent=minsToText(m.m)+' Std.';$('#monthPay').textContent=euro(m.p)+' gesamt';$('#paidPay').textContent=euro(p.p);$('#paidMeta').textContent=p.n+' Einträge';$('#billOpen').textContent=euro(a.p);$('#billBilled').textContent=euro(totals(entries.filter(e=>e.status==='billed')).p);renderRecent();renderList()}
function renderRecent(){let x=[...entries].sort((a,b)=>b.date.localeCompare(a.date)||b.created-a.created).slice(0,4);$('#recent').innerHTML=x.length?x.map(rowHTML).join(''):'<div class="hint">Noch keine Arbeitszeiten gespeichert.</div>';bindRows($('#recent'))}
function rowHTML(e){return `<div class="row" data-id="${e.id}"><div class="rowtop"><div><b>${dateDE(e.date)}</b><div class="meta">${e.start}–${e.end} · Pause ${e.pause} Min. · ${minsToText(e.minutes)} Std.</div>${e.note?`<div class="meta">${esc(e.note)}</div>`:''}</div><div class="money">${euro(e.amount)}</div></div><span class="status ${e.status}">${e.status==='open'?'Offen':e.status==='billed'?'Abgerechnet':'Bezahlt'}</span><div class="rowactions"><button data-action="next">${e.status==='open'?'Als abgerechnet':e.status==='billed'?'Als bezahlt':'Wieder öffnen'}</button><button data-action="edit">Bearbeiten</button><button data-action="delete" class="danger">Löschen</button></div></div>`}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderList(){if(!$('#entries'))return;let f=$('#filter').value,m=$('#monthFilter').value;let list=[...entries].filter(e=>(f==='all'||e.status===f)&&(!m||e.date.startsWith(m))).sort((a,b)=>b.date.localeCompare(a.date)||a.start.localeCompare(b.start));let groups={};list.forEach(e=>(groups[e.date]??=[]).push(e));$('#entries').innerHTML=Object.entries(groups).map(([d,arr])=>{let t=totals(arr);return `<div class="day"><div class="dayhead"><span>${dateDE(d)}</span><span class="daytotal">${minsToText(t.m)} Std. · ${euro(t.p)}</span></div>${arr.map(rowHTML).join('')}</div>`}).join('')||'<div class="hint">Für diese Auswahl gibt es keine Einträge.</div>';bindRows($('#entries'))}
function bindRows(root){root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{let id=b.closest('.row').dataset.id,e=entries.find(x=>x.id===id);if(!e)return;if(b.dataset.action==='delete'){if(confirm('Diesen Arbeitseintrag wirklich löschen?')){entries=entries.filter(x=>x.id!==id);save()}}else if(b.dataset.action==='next'){e.status=e.status==='open'?'billed':e.status==='billed'?'paid':'open';e.paidAt=e.status==='paid'?new Date().toISOString():null;save()}else{loadEdit(e)}})}
function loadEdit(e){nav('entry');$('#date').value=e.date;$('#start').value=e.start;$('#end').value=e.end;$('#pause').value=e.pause;$('#rate').value=e.rate;$('#note').value=e.note||'';$('#entryForm').dataset.edit=e.id;updateCalc();window.scrollTo(0,0)}
function updateCalc(){let m=calcMins($('#start').value,$('#end').value,$('#pause').value),amt=m/60*(+$('#rate').value||0);$('#calc').textContent=`Netto: ${minsToText(m)} Std. · ${euro(amt)}`}
$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));['start','end','pause','rate'].forEach(id=>$('#'+id).addEventListener('input',updateCalc));
$('#entryForm').onsubmit=e=>{e.preventDefault();let m=calcMins($('#start').value,$('#end').value,$('#pause').value);if(m<=0)return alert('Bitte Arbeitszeit und Pause prüfen.');let obj={id:$('#entryForm').dataset.edit||crypto.randomUUID(),date:$('#date').value,start:$('#start').value,end:$('#end').value,pause:+$('#pause').value||0,rate:+$('#rate').value||0,note:$('#note').value.trim(),minutes:m,amount:Math.round(m/60*(+$('#rate').value||0)*100)/100,status:'open',created:Date.now()};let old=entries.find(x=>x.id===obj.id);if(old){obj.status=old.status;obj.created=old.created;obj.paidAt=old.paidAt;entries=entries.map(x=>x.id===obj.id?obj:x)}else entries.push(obj);delete $('#entryForm').dataset.edit;let rate=obj.rate;$('#entryForm').reset();$('#date').value=new Date().toISOString().slice(0,10);$('#rate').value=rate;$('#pause').value=0;save();nav('overview')}
$('#filter').onchange=renderList;$('#monthFilter').onchange=renderList;$('#menuBtn').onclick=()=>$('#menu').classList.remove('hidden');$('#closeMenu').onclick=()=>$('#menu').classList.add('hidden');$('#about').onclick=()=>{$('#menu').classList.add('hidden');$('#aboutBox').classList.remove('hidden')};$('#closeAbout').onclick=()=>$('#aboutBox').classList.add('hidden');
function download(name,text,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#backup').onclick=()=>download(`zeitzwerk-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({app:'Zeit(z)Werk',version:1,exported:new Date().toISOString(),entries},null,2),'application/json');
$('#restore').onchange=async ev=>{let f=ev.target.files[0];if(!f)return;try{let j=JSON.parse(await f.text());if(!Array.isArray(j.entries))throw 0;if(confirm(`${j.entries.length} Einträge aus der Sicherung laden? Die aktuellen Daten werden ersetzt.`)){entries=j.entries;save();alert('Datensicherung wurde wiederhergestellt.')}}catch{alert('Diese Datei ist keine gültige Zeit(z)Werk-Sicherung.')}ev.target.value=''};
$('#csv').onclick=()=>{let h=['Datum','Beginn','Ende','Pause_Min','Netto_Std','Stundenlohn_EUR','Betrag_EUR','Status','Notiz'];let lines=[h,...[...entries].sort((a,b)=>a.date.localeCompare(b.date)).map(e=>[e.date,e.start,e.end,e.pause,(e.minutes/60).toFixed(2).replace('.',','),e.rate.toFixed(2).replace('.',','),e.amount.toFixed(2).replace('.',','),e.status,e.note||''])];download('zeitzwerk-export.csv','\ufeff'+lines.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n'),'text/csv;charset=utf-8')};
function printFiltered(openOnly){nav('calendar');if(openOnly)$('#filter').value='open';renderList();setTimeout(()=>window.print(),100)}$('#printOpen').onclick=()=>printFiltered(true);$('#printAll').onclick=()=>printFiltered(false);
$('#date').value=new Date().toISOString().slice(0,10);$('#monthFilter').value=new Date().toISOString().slice(0,7);setTimeout(()=>{$('#splash').classList.add('hidden');$('#app').classList.remove('hidden');render()},1200);
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
